"__kernel void solveLeaf(const __global long *clauses, const __global long *numVarsC, long numclauses,\n"
"                        __global long *solutions, long numV, const __global long *vertices) {\n"
"    uint id = get_global_id(0);\n"
"    for (i = 0; i < numV; i++) {\n"
"        solutions[(numV + 1) * id + i] = 5;\n"
"    }\n"
"}\n"